"""Letterhead router — public downloads for Umar's reusable company letterhead.

Serves two artefacts generated by ``letterhead.py``:
  * GET /api/letterhead.pdf  — print-ready A4 PDF
  * GET /api/letterhead.docx — editable Word template for OneDrive

These are intentionally public (no auth) so Umar can:
  1. Open the URLs directly from any browser / phone and tap "Save to Files"
  2. Share the URL with a lawyer / accountant without granting dashboard access
  3. Upload the DOCX directly into OneDrive from the Download card on /admin

Both responses carry `Content-Disposition: attachment` so browsers prompt
the user to save rather than render inline (which would strip the DOCX
when Word Online isn't the system handler).
"""
from __future__ import annotations

from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from io import BytesIO

from letterhead import build_letterhead_pdf, build_letterhead_docx

router = APIRouter()


@router.get("/letterhead.pdf")
async def letterhead_pdf():
    """Serve the print-ready A4 letterhead PDF."""
    pdf_bytes = build_letterhead_pdf()
    return StreamingResponse(
        BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={
            "Content-Disposition": 'attachment; filename="Vaulted-Letterhead.pdf"',
            "Cache-Control": "public, max-age=3600",
        },
    )


@router.get("/letterhead.docx")
async def letterhead_docx():
    """Serve the editable Word letterhead template (OneDrive-friendly)."""
    docx_bytes = build_letterhead_docx()
    return StreamingResponse(
        BytesIO(docx_bytes),
        media_type=(
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        ),
        headers={
            "Content-Disposition": 'attachment; filename="Vaulted-Letterhead.docx"',
            "Cache-Control": "public, max-age=3600",
        },
    )
